### ISSUE TITLE
Property 'atob' doesn't exist when using in react native

### ISSUE THREAD

**Issue by bored-jrb** [deso-protocol/deso-js#2]
I want to use this for react native but keep getting the following when using identity or just about anything after importing from deso-protocol:
"Property 'atob' doesn't exist" 
--- or ---
 ERROR  ReferenceError: Property 'atob' doesn't exist, js engine: hermes

Which leads me to believe that dependencies for this package are more structured for web use. Could I get some clarity on this if its not ready for react native/expo or get an explanation in applying this with my react native project?

**Comment by jackson-dean** [comment]
You are correct, this library and it's dependencies are for web applications and it will not work for react native. I am working on a separate library for react native since the environment and dependencies needed will be quite different. I am hoping to have something in a beta state for this soon. I will update on this thread issue thread once it is available for testing.

**Comment by Joker-io** [comment]
Awesome, thank you for clarifying. Looking forward to it! 🙌🏻

**Comment by jackson-dean** [comment]
@bored-jrb I spent some time on this over the past week and have a beta version available for testing. I added some docs for how to get it running in react native https://github.com/deso-protocol/deso-js#react-native-beta
I'm also working on an example repo that's using react native which I will try to have ready to make public sometime next week.
